// Generated by Fabrica dev
// Template: init/go.mod.tmpl
// Generated: 2025-11-21T12:58:51-08:00

module github.com/example/inventory-v3

go 1.23.4

toolchain go1.24.3

require (
	github.com/go-chi/chi/v5 v5.0.10
	github.com/openchami/fabrica v0.3.1
	github.com/spf13/cobra v1.10.1
	github.com/spf13/viper v1.16.0
	gopkg.in/yaml.v3 v3.0.1
)

require golang.org/x/text v0.23.0 // indirect

replace github.com/openchami/fabrica v0.3.1 => /Users/ben.mcdonald/fabrica
